# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3458a7c47a4d2ecfe5d57b7e359acc014ae72d0e67c7fa9399c24f1b352ff731361cac450c2dd4417b06dba0e397a8dacd2485fb9f86dad9e2c66a0254025adf

test:
  secret_key_base: ad1ef02df37478db42d3925c75e7be8cc437250b16ba4a8810f24505eae4971510a778d8f36a4e3d67ffc0607cdb1e22fd782d7f479d85206eb213e8bf04af39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
